<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application.Abstractions\Application.Abstractions.csproj" />
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure.Media\Infrastructure.Media.csproj" />
    <ProjectReference Include="..\Infrastructure.Vitrivr\Infrastructure.Vitrivr.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
