from argparse import ArgumentParser
from pathlib import Path


DOCS_DIR = Path(__file__).resolve().parent
CLEAN_ROOTS = (
    DOCS_DIR / "Evaluation",
    DOCS_DIR / "Presentation",
    DOCS_DIR / "Report",
    DOCS_DIR / "WeeklyMeeting",
)

# Only files generated by LaTeX/BibTeX/latexmk are removed. Source files such as
# .tex, .bib, .sty, .bst, PDFs, images and diagrams are intentionally preserved.
GENERATED_SUFFIXES = (
    ".aux",
    ".bbl",
    ".bcf",
    ".blg",
    ".fdb_latexmk",
    ".fls",
    ".ilg",
    ".ind",
    ".idx",
    ".lof",
    ".log",
    ".lot",
    ".nav",
    ".nlo",
    ".nls",
    ".out",
    ".run.xml",
    ".snm",
    ".synctex.gz",
    ".toc",
    ".vrb",
    ".xdv",
)


def is_generated_latex_file(path: Path) -> bool:
    return path.is_file() and path.name.endswith(GENERATED_SUFFIXES)


def cleanup(dry_run: bool) -> int:
    deleted = 0

    for root in CLEAN_ROOTS:
        if not root.exists():
            continue

        for path in sorted(root.rglob("*")):
            if not is_generated_latex_file(path):
                continue

            relative_path = path.relative_to(DOCS_DIR)
            if dry_run:
                print(f"Wuerde loeschen: {relative_path}")
            else:
                path.unlink()
                print(f"Geloescht: {relative_path}")
            deleted += 1

    return deleted


def main() -> None:
    parser = ArgumentParser(
        description="Remove generated LaTeX files from docs document folders."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only list files that would be deleted.",
    )
    args = parser.parse_args()

    count = cleanup(args.dry_run)
    action = "gefunden" if args.dry_run else "geloescht"
    print(f"{count} generierte Datei(en) {action}.")


if __name__ == "__main__":
    main()
